services:
  app:
    container_name: mqtt2_mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - #jeedom_path#/plugins/mqtt2/resources/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - #jeedom_path#/logs/mqtt2_mosquittod:/mosquitto/log/mosquitto.log