services:
  app:
    container_name: mqtt2_mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports:
#ports#
    volumes:
      - #jeedom_path#/plugins/mqtt2/data/ssl:/mosquitto/config/ssl
      - #jeedom_path#/plugins/mqtt2/data/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - #jeedom_path#/plugins/mqtt2/data/passwords:/mosquitto/passwords